[package]
name = "luci"
version = "0.1.0"
authors = ["knh190 <knh190@hotmail.com>"]
edition = "2018"

[dependencies]
# ui
iced = { version = "0.2.0", features = ["image"] }
iced_native = "0.3"   # events
iced_graphics = "0.1" # render

# logger
slog = "2.7"
sloggers = "*"

# serialize
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# mesh
tobj = "2.0.4"

# image
image = "0.23"

# 3d math
glam = { version = "0.13", features = ["serde"] }

# utils
clap = "2.33" # cmd parser
dirs = "3.0" # relative dir convert
anyhow = "*" # handle error
